### ISSUE TITLE
missing dependent scripts/variables for Phil_ERTrealexample.m

### ISSUE THREAD

**Issue by dakota-palmer** [philjrdb/ERTsimulation#2]
I think these can probably all be worked around, but I got errors when I tried to run this script because the following variables/functions were missing:

**variables**
Aggregate_Cp_off_Acq1sup_keep
Acq3sup_keep
col_rep

**functions**
sem()
errorplot3()

**Comment by philjrdb** [comment]
Thanks for letting me know!

I've uploaded sem.m, errorplot3.m, col_rep.m - they're just functions to help plot results.

The lines using other variables were unnecessary lines of code (originally used to transfer data into ERT_test structure, which is posted).

**Comment by lisahiura** [comment]
I might be overlooking it, but I still don't see col_rep.m. Is that available?

**Comment by philjrdb** [comment]
Apologies - I've uploaded col_rep.m (it's just a standardised repository of colours for the lab).
